TRUNCATE customers;
INSERT INTO customers (acc_num, card_balance, card_id, Age, Gender, Count, AverageMonthlyExpenditures, Flag, Id, Address, Email) VALUES
( 1, 10, 'card1', 21,0,0,0,'Y','Y','Y','Y');
INSERT INTO customers (acc_num, card_balance, card_id, Age, Gender, Count, AverageMonthlyExpenditures, Flag, Id, Address, Email) VALUES
( 2, -90, 'card1', 48,0,0,0,'Y','Y','Y','Y');
INSERT INTO customers (acc_num, card_balance, card_id, Age, Gender, Count, AverageMonthlyExpenditures, Flag, Id, Address, Email) VALUES
( 3, 11, 'card1', 43,0,0,0,'Y','Y','Y','Y');
INSERT INTO customers (acc_num, card_balance, card_id, Age, Gender, Count, AverageMonthlyExpenditures, Flag, Id, Address, Email) VALUES
( 4, 591, 'card1', 91,0,0,0,'Y','Y','Y','Y');
INSERT INTO customers (acc_num, card_balance, card_id, Age, Gender, Count, AverageMonthlyExpenditures, Flag, Id, Address, Email) VALUES
( 6, -8, 'card1', 61,0,0,0,'Y','Y','Y','Y');
INSERT INTO customers (acc_num, card_balance, card_id, Age, Gender, Count, AverageMonthlyExpenditures, Flag, Id, Address, Email) VALUES
( 7, 1998, 'card1', 32,0,0,0,'Y','Y','Y','Y');
INSERT INTO customers (acc_num, card_balance, card_id, Age, Gender, Count, AverageMonthlyExpenditures, Flag, Id, Address, Email) VALUES
( 8, 67, 'card1', 37,0,0,0,'Y','Y','Y','Y');
INSERT INTO customers (acc_num, card_balance, card_id, Age, Gender, Count, AverageMonthlyExpenditures, Flag, Id, Address, Email) VALUES
( 5, 123, 'card1', 16,0,0,0,'Y','Y','Y','Y');
INSERT INTO customers (acc_num, card_balance, card_id, Age, Gender, Count, AverageMonthlyExpenditures, Flag, Id, Address, Email) VALUES
( 9, -819, 'card1', 70,0,0,0,'Y','Y','Y','Y');
INSERT INTO customers (acc_num, card_balance, card_id, Age, Gender, Count, AverageMonthlyExpenditures, Flag, Id, Address, Email) VALUES
(10, -71, 'card1', 19,0,0,0,'Y','Y','Y','Y');
INSERT INTO customers (acc_num, card_balance, card_id, Age, Gender, Count, AverageMonthlyExpenditures, Flag, Id, Address, Email) VALUES
(1, 400, '403733', 19,0,0,0,'Y','Y','Y','Y');

SELECT * FROM customers;